services:
  - type: web
    name: ps-crm
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/users/pending-officers
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: AI_API_KEY
        sync: false
      - key: AI_MODEL
        value: meta-llama/llama-3.1-8b-instruct:free
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        sync: false
